### ISSUE TITLE
我使用php7

### ISSUE THREAD

**Issue by ndj888** [Coxxs/discuzx-php7-patch#1]
Discuz! System Error

Function name must be a string
PHP Debug

No. File    Line    Code
1   forum.php   65  runhooks()
2   source/function/function_core.php   1122    hookscript(%s, %s, %s, Array, %s)
3   source/function/function_core.php   1171    break()
www.chdhd.cc 已经将此出错信息详细记录, 由此给您带来的访问不便我们深感歉意.

**Comment by Coxxs** [comment]
Hi! 由于 Discuz! F 提供了更完善的 PHP 7 支持，因此本项目将不再继续维护。非常抱歉。

Discuz! F：http://www.discuz.net/thread-3778501-1-1.html
